import Head from "next/head";
import styles from "../styles/Home.module.scss";
import About from "../components/about/about.tsx";
import Footer from "../components/footer/footer.tsx";
import Home from "../components/home/home.tsx";
import Navbar from "../components/navbar/navbar.tsx";
import WorkExperience from "../components/work-experience/work-experience.tsx";

export default function index() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Alireza Rezaei</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.app}>
        <Navbar />
        <Home />
        <WorkExperience />
        <About />
        <Footer />
      </div>
    </div>
  );
}
